ARG REPO=
ARG VER=15.5
FROM ${REPO}infrastlabs/x11-base:rootfs AS rootfs

# FROM opensuse/leap:${VER}
FROM registry.cn-shenzhen.aliyuncs.com/infrasync/v2025:opensuse--leap---${VER}
ARG TARGETPLATFORM
ARG TYPE=core
ARG VER=15.5
# zyp-source
# http://mirrors.ustc.edu.cn/help/opensuse.html
# https://blog.csdn.net/zhuzhenyu215/article/details/133523918
# mirrors.ustc.edu.cn  mirrors.aliyun.com  +mirrors.163.com
#  ustc: 15.4+ https://mirrors.ustc.edu.cn/opensuse/distribution/leap/
#  ali: 15.2+ https://mirrors.aliyun.com/opensuse/distribution/leap/
#  TODO: 15.0-gtk2@163 http://mirrors.163.com/openSUSE/distribution/leap/15.0/repo/
#   https://mirrors.163.com/openSUSE/distribution/leap/15.0/repo/oss/
#   https://mirrors.163.com/openSUSE/distribution/leap/15.0/repo/non-oss/
RUN \
  # test "15.0" != "${VER}" && exit 0; \
  \
  # export dm="mirrors.ustc.edu.cn"; \
  # zypper ar -fc https://$dm/opensuse/distribution/leap/${VER}/repo/oss openSUSE-Asia-OSS; \
  # zypper ar -fc https://$dm/opensuse/distribution/leap/${VER}/repo/non-oss openSUSE-Asia-NON-OSS; \
  # zypper ar -fc https://$dm/opensuse/update/leap/${VER}/oss openSUSE-Asia-UPDATE-OSS; \
  # zypper ar -fc https://$dm/opensuse/update/leap/${VER}/non-oss openSUSE-Asia-UPDATE-NON-OSS; \
  \
  # avoid existed
  cd /etc/zypp/repos.d && ls |grep Asia |while read one; do rm -f $one; done; \
  # 163: opensuse> openSUSE
  export dm="mirrors.163.com/openSUSE"; \
  test "15.6" == "${VER}" && export dm="mirrors.ustc.edu.cn/opensuse"; \
  zypper ar -fc https://$dm/distribution/leap/${VER}/repo/oss openSUSE-Asia-OSS; \
  zypper ar -fc https://$dm/distribution/leap/${VER}/repo/non-oss openSUSE-Asia-NON-OSS; \
  zypper ar -fc https://$dm/update/leap/${VER}/oss openSUSE-Asia-UPDATE-OSS; \
  zypper ar -fc https://$dm/update/leap/${VER}/non-oss openSUSE-Asia-UPDATE-NON-OSS; \
  \
  cd /etc/zypp/repos.d && ls |grep -v Asia |while read one; do rm -f $one; done; \
  find /etc/zypp/repos.d; \
  zypper clean; rm -rf /var/cache/zypp;
RUN \
  echo 'zypper install -y $@ && zypper clean; rm -rf /var/cache/zypp; ' > /usr/local/bin/zyp.sh \
    && chmod +x /usr/local/bin/zyp.sh; 
  # 刷新更新
  # zypper refresh; 

# zypper clean && zypper refresh \
# ping: @iputils
#  v15.0_none?: wget zip unzip 
RUN \
  zyp.sh iproute net-tools \
  sudo psmisc sysstat tree tmux lrzsz which openssl \
  iputils wget zip unzip \
  procps jq \
  tar gzip vim \
  lame; \
  # test "15.0" != "${VER}" && zyp.sh wget zip unzip ; \
  # 01: chmod u+s /bin/ping #02: sudo setcap cap_net_raw+p /bin/ping #setcap 无指令
  chmod u+s /bin/ping; \
  exit 0

# ibrsvg for icons
#  zyp-ex: tzdata dbus-x11
#  locales: glibc-locale
RUN \
  zyp.sh thunar librsvg-2-2

##APP################################################
# 0.07 Mbs	hicolor-icon-theme-0.17-noarch
# 0.34 Mbs	adwaita-xfce-icon-theme-0.0.2+git0.ee9b710-noarch
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  zyp.sh \
  hicolor-icon-theme adwaita-xfce-icon-theme; \
  # LoginIcons Humanity* ubuntu-mono* 
  cd /usr/share/icons && rm -rf Tango adwaita-xfce; \
  exit 0

# gpg check failed too? @alma 8.7
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  zyp.sh firefox; \
  exit 0

# sakura+
# zyp-ex: clipit pnmixer 
# plank rofi clipit pnmixer lxappearance thunar \
# tint2
# pnmixer> pasystray
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  zyp.sh pavucontrol pasystray xrandr \
  ibus ibus-rime flameshot \
  sakura thunar lxappearance   geany ristretto engrampa gnome-system-monitor; \
  exit 0

# XFCE4
  # xfdesktop4 > xfdesktop @opsuse15.5
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  # 2536 kB #18.9 MB > 14.3 MB
  echo a.123; \
  zyp.sh \
  xfwm4 xfdesktop \
  xfce4-notifyd xfce4-settings xfce4-session; \
  exit 0

# locales dconf-cli gtk2-engines-pixbuf x11-xkb-utils
#  zyp-ex: tzdata dbus-x11
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  zyp.sh binutils at-spi2-core xdg-utils \
  # lanpacks: rhel>> yum install langpacks-zh_CN;
  glibc-locale plank \
  # xrdb-font
  xrdb git \
  # vim, locale, ping; ubt:iptuils-ping; vim 2.2M;
  iputils vim scrot \
  # dbus-x11: perp> xfce4-session: err #hand run> xfce4-session: ok
  dbus-1-x11; \
  exit 0


# HEADLESS
COPY --from=rootfs /rootfs/res_ubt_share /
COPY --from=rootfs /rootfs/files1 /
COPY --from=rootfs /rootfs/files2 /
RUN \
  bash /xconf.sh core; bash /xconf.sh app; \
  exit 0;

# HEADLESS2
# COPY --from=res / /

# EXPOSE 10089/tcp 10081/tcp 10022/tcp
CMD ["bash", "-c", "exec /entry.sh"]
ENV \
  TERM=xterm \
  SHELL=/bin/bash

# Set multiple labels at once, author,builtdate
ARG BUILDDATE
LABEL \
  github.com.infrastlabs.docker-x11base.vendor=Infrastlabs \
  github.com.infrastlabs.docker-x11base.release="production" \
  github.com.infrastlabs.docker-x11base.version="1.0.1-beta" \
  github.com.infrastlabs.docker-x11base.maintainer="sam <sldevsir@126.com>" \
  github.com.infrastlabs.docker-x11base.builtdate="$BUILDDATE"
