ARG REPO=
ARG VER=1.36.1
FROM ${REPO}infrastlabs/x11-base:rootfs AS rootfs
FROM registry.cn-shenzhen.aliyuncs.com/infrasync/v2025:library--busybox---${VER}
# # sed grep gawk bash; curl wget
# RUN apk add --no-cache \
#   ca-certificates tzdata curl wget \
#   sed grep gawk findutils sudo tree unzip procps htop \
#   expect shadow xterm bash bash-completion coreutils busybox-extras \
#   \
#   lftp jq sysstat lame 

RUN \
  wget -O /bin/bash --no-check-certificate https://github.com/robxu9/bash-static/releases/download/5.2.015-1.2.3-2/bash-linux-x86_64; \
  chmod +x /bin/bash; chmod u+s /bin/ping; exit 0
# DO bash-static@rfs

# HEADLESS
COPY --from=rootfs /rootfs/res_ubt_share /
COPY --from=rootfs /rootfs/files1 /
COPY --from=rootfs /rootfs/files2 /
RUN ln -s /usr/local/static/3rd/bin/bash /bin/; \
  bash /xconf.sh core; exit 0

# EXPOSE 10089/tcp 10081/tcp 10022/tcp
CMD ["bash", "-c", "exec /entry.sh"]
ENV \
  TERM=xterm \
  SHELL=/bin/bash

# Set multiple labels at once, author,builtdate
ARG BUILDDATE
LABEL \
  github.com.infrastlabs.docker-x11base.vendor=Infrastlabs \
  github.com.infrastlabs.docker-x11base.release="production" \
  github.com.infrastlabs.docker-x11base.version="1.0.1-beta" \
  github.com.infrastlabs.docker-x11base.maintainer="sam <sldevsir@126.com>" \
  github.com.infrastlabs.docker-x11base.builtdate="$BUILDDATE"
